# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'example.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgMain(object):
    def setupUi(self, DlgMain):
        DlgMain.setObjectName("DlgMain")
        DlgMain.resize(449, 479)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        DlgMain.setFont(font)
        DlgMain.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.grbDialog = QtWidgets.QGroupBox(DlgMain)
        self.grbDialog.setGeometry(QtCore.QRect(10, 0, 421, 261))
        self.grbDialog.setAlignment(QtCore.Qt.AlignCenter)
        self.grbDialog.setCheckable(True)
        self.grbDialog.setChecked(True)
        self.grbDialog.setObjectName("grbDialog")
        self.lbl1 = QtWidgets.QLabel(self.grbDialog)
        self.lbl1.setGeometry(QtCore.QRect(20, 30, 81, 16))
        self.lbl1.setObjectName("lbl1")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.grbDialog)
        self.dateTimeEdit.setGeometry(QtCore.QRect(10, 60, 194, 24))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalSlider = QtWidgets.QSlider(self.grbDialog)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 120, 160, 22))
        self.horizontalSlider.setMaximum(199)
        self.horizontalSlider.setSliderPosition(50)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.listWidget = QtWidgets.QListWidget(self.grbDialog)
        self.listWidget.setGeometry(QtCore.QRect(235, 20, 221, 192))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.lcdNumber = QtWidgets.QLCDNumber(self.grbDialog)
        self.lcdNumber.setGeometry(QtCore.QRect(10, 170, 171, 61))
        self.lcdNumber.setObjectName("lcdNumber")
        self.lineEdit = QtWidgets.QLineEdit(DlgMain)
        self.lineEdit.setGeometry(QtCore.QRect(10, 280, 421, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(DlgMain)
        self.label.setGeometry(QtCore.QRect(10, 310, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(DlgMain)
        self.horizontalSlider.valueChanged['int'].connect(self.lcdNumber.display)
        self.lineEdit.textChanged['QString'].connect(self.label.setText)
        QtCore.QMetaObject.connectSlotsByName(DlgMain)
        DlgMain.setTabOrder(self.horizontalSlider, self.grbDialog)
        DlgMain.setTabOrder(self.grbDialog, self.dateTimeEdit)
        DlgMain.setTabOrder(self.dateTimeEdit, self.listWidget)

    def retranslateUi(self, DlgMain):
        _translate = QtCore.QCoreApplication.translate
        DlgMain.setWindowTitle(_translate("DlgMain", "My GUI"))
        self.grbDialog.setTitle(_translate("DlgMain", "My GUI Widgets"))
        self.lbl1.setText(_translate("DlgMain", "First Widget"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("DlgMain", "Item1"))
        item = self.listWidget.item(1)
        item.setText(_translate("DlgMain", "Item2"))
        item = self.listWidget.item(2)
        item.setText(_translate("DlgMain", "Item3"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.lineEdit.setPlaceholderText(_translate("DlgMain", "Input something here"))
